version: '3.4'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rinha 
      POSTGRES_USER: rinha 
      POSTGRES_DB: rinha
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '1.30GB'

  api1: &app
    restart: always
    image: rinha
    hostname: api1
    build:
      context: .
      dockerfile: src/Rinha.Api/Dockerfile
    #environment:
    # - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.70GB'
  api2:
    <<: *app
    hostname: api2
    environment:
    # - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://*:3001
    depends_on: 
      - db
      - api1

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.30GB'