# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rinha 
      POSTGRES_USER: rinha 
      POSTGRES_DB: rinha
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  api1:
    image: rinha
    hostname: api1
    build:
      context: .
      dockerfile: src/Rinha.Api/Dockerfile
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - db
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api2:
    image: rinha
    hostname: api2
    build:
      context: .
      dockerfile: src/Rinha.Api/Dockerfile
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - db
      - api1
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

networks:
  rinha-network:
    driver: bridge